package bk.devoxx17.front;

public enum InjectionMethod {
	CLASSICAL, 
	CLASSICAL_DELUXE,
	UNION_EXPLOIT, 
	UNION_EXPLOIT_DELUXE,
	STACKED_QUERIES
//	SOCIAL_HACK_KEYBOARD, 
//	SOCIAL_HACK_HUMAN,
//	KONAMI
}
